version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app   # Mount app folder into container
    working_dir: /app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload